Add a section about the rights of end users
InspireNL/GDPR-Checklist-for-Sites-and-Apps pull request #2
Opened 2018-03-08 07:55 UTC by jakeprins

2018-03-08 10:15 UTC, florisvlasveld commented
@Joralf Do you have additional comments/suggestions?

2018-03-13 11:12 UTC, jakeprins commented
@Joralf Do you have some comments? Also feel free to add a PR if you have some improvements in mind.

2018-03-15 16:02 UTC, florisvlasveld requested changes

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
> +- [ ] The application does not collect more data then it needs.
I would propose to clarify that the application does not collect more data **than is needed to fulfil the goal as communicated to the end user**.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
> +- [ ] End users can view and adjust data that is actively shared (by the user).
Perhaps good to clarify that this involves personal data (and not e.g. generated log data by the system, as long as that log data does not contain personal data).

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
> +- [ ] If the application includes decision-making, it should be clear how that decision is taken. [(Example)](#decision-making)
**automated** decision making **that has a significant impact on the user**.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
> +- [ ] An appropriate assessment has been made when data is [pseudonymized](#pseudonymisation) and this process is tuned. [(Example)](#pseudonymised-data)
I don't really understand this sentence. Can you clarify?

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
> +  * the ability to restore the availability and access to personal data in a timely manner in the event of a physicl or technical incident.
Typo: **physical**.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
>  * End users can file a complaint.
Doesn't have to be system-supported. But must be mentioned in the privacy statement.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
> +* End users have the option to withdraw their consent.
In most cases (focus on software) this would mean that the user is deleted from the system. Perhaps good to clarify that.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
>  * End users have the right to obtain their personal data that he has provided to a processor, in a structured, current and machine-readable form, and he has the right to transfer this data to another
Perhaps good to clarify what type of data we're talking about. E.g. as far as I know, the provided answers to questions in TopiaTrainer do not need to be transferred as these are not personal data. However, for KankerNL, I could imagine being able to retrieve your medical profile from the system is indeed a requirement.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
> +
I'm not entirely sure this (the register) is true. In which part of the AVG document did you read this?

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
>  * If the controller pursues a different purpose with the data then has been reported in advance, this must be communicated to the end user.
.. **before commencing the processing of data for that purpose**.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
>  * The [processor](#processor) does not employ another processor without the prior written consent of the controller.
Perhaps good to clarify in this document who the controller and who the processors are.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
There are a few more requirements. See for example https://www.bullhorn.com/nl/blog/2017/07/gdpr-avg-en-privacy-statements/.

2018-03-15 16:02 UTC, florisvlasveld commented on README.md
>  * Political opinions
I think there are more categories, such as medical data and data about children. See e.g. https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/lawful-basis-for-processing/special-category-data/.

2018-03-20 11:50 UTC, florisvlasveld approved these changes

2018-03-20 15:47 UTC, merged